# Generated by Django 5.2.6 on 2025-10-14 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nim', models.CharField(max_length=15, unique=True)),
                ('nama', models.CharField(max_length=100)),
                ('programstudi', models.CharField(max_length=50)),
            ],
        ),
    ]
